config/routes.rb
Rails.application.routes.draw do
  get 'bookings', to:'bookings#new'
  post 'bookings', to:'bookings#create'
  get 'bookings/:id', to:'bookings#show'
  post '/checkout/create', to: 'checkout#create'
  get '/flights', to:'flights#index'
  get '/passengers/:id', to:'passengers#confirm_email'
  root 'flights#index'
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, class_name: "Flight", foreign_key: "departure_airport_id", dependent: :delete_all
  has_many :arriving_flights, class_name: "Flight", foreign_key: "arrival_airport_id", dependent: :delete_all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers
  accepts_nested_attributes_for  :passengers
  
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: "Airport"
  belongs_to :arrival_airport, class_name: "Airport"
  has_many :bookings
  has_many :passengers, through: :bookings
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking

  validates_uniqueness_of :name, scope: :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @flight = Flight.find(params[:flight_id])
    n_passengers = params[:passengers].to_i
    n_passengers.times { @booking.passengers.build }
    @price = (@flight.price * n_passengers).to_f.round(2)
  end

  def create
    @booking = Booking.new(params_booking)
    if @booking.save
      flight = Flight.find(params[:booking][:flight_id])
      flight.seats_left -= params[:booking][:passengers_attributes].keys.length
      flight.save!
      @booking.passengers.each{ |passenger| PassengerMailer.with(passenger: passenger).confirmation_email.deliver_now! }
      redirect_to action: "show", id: @booking.id
    else
      puts booking.errors.full_messages
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private
    def params_booking
      params.require(:booking).permit(:flight_id, passengers_attributes:[:name, :email])
    end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def create
    booking = Booking.find(params[:id])
    @session = Stripe::Checkout::Session.create({
      payment_method_types: ['card'],
      line_items: [
		name: "Booking Id:#{booking.id}",
		quantity: booking.passengers.length,
		amount: (booking.flight.price.to_f*100).round,
		currency: 'usd'
      ],
      mode: 'payment',
      success_url: root_url,
      cancel_url: root_url,
    }) 
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @airport_codes = Airport.all.to_a.map{|airport| [airport.code,airport.id]}
    @airport_codes.unshift(["Code","0"])
    @passengers = Array.new(5).map.with_index{|v,i| i}
    @dates = Flight.all.to_a.map{ |flight| flight.start_datetime }.sort.map{ |date| date.strftime("%d/%m/%Y") }.uniq
    @dates.unshift("Date")
    where_str = ""
    if params[:from_airport]
      where_str += " departure_airport_id = " + params[:from_airport]
    end
    if params[:to_airport]
      where_str += " AND " unless where_str == ""
      where_str += " arrival_airport_id = "+ params[:to_airport]
    end
    if params[:passengers]
      where_str += " AND " unless where_str == ""
      where_str += " seats_left >= " + params[:passengers]
    end
    if params[:date]
      where_str += " AND " unless where_str == ""
      date = DateTime.strptime(params[:date],'%d/%m/%Y')
      next_date = date + 1.day
      where_str += " start_datetime BETWEEN '" + date.strftime('%Y-%m-%d 00:00:00') + "' AND '"+next_date.strftime('%Y-%m-%d 00:00:00')+"'"
    end
    puts where_str
    unless where_str == ""
      @flights = Flight.includes(:departure_airport, :arrival_airport).where(where_str)
    end
  end
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
  def confirm_email
    passenger = Passenger.find(params[:id])
    passenger.email_confirmed = true
    passenger.save
    redirect_to "/bookings/#{passenger.booking.id}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/new.html.erb
<h1>Flight: <%= @flight.id %></h1>
<p>Price to pay: <%= @price %></p>
<p><strong>Departure Airport: </strong><%= @flight.departure_airport.code %></p>
<p><strong>Arrival Airport: </strong><%= @flight.arrival_airport.code %></p>
<p><strong>Duration: </strong><%= @flight.duration.floor %> hours <%= (@flight.duration.modulo(1)*60).to_i %> minutes</p>
<p><strong>Start Datetime: </strong><%= @flight.start_datetime %></p>
<p><strong>Seats Left: </strong><%= @flight.seats_left %></p>

<%= form_with model: @booking do |f| %>
  <%= f.hidden_field :flight_id, value: @flight.id %>
    <%= f.fields_for :passengers do |sf| %>
      <article>
        <%= sf.label :name %>
        <%= sf.text_field :name %>
        <%= sf.label :email %>
        <%= sf.text_field :email %>
      </article>
      <br />
    <% end %>
  <%= f.submit %>
<% end %>

app/views/bookings/show.html.erb
<h1>Booking: <%= @booking.id %></h1>
<h3>Passengers:</h3>
<% @booking.passengers.each do |passenger| %>
  <article><strong>Name:</strong> <%= passenger.name %> <strong>Email:</strong> <%= passenger.email %><article> 
<% end %>
<%= button_to "Pay Now!", checkout_create_path, params: {id: @booking.id}, remote: true %>

app/views/checkout/create.js.erb
var stripe = Stripe("<%=Rails.application.credentials.stripe[:public_key]%>");
var checkoutButton = document.getElementById('checkout-button');

//checkoutButton.addEventListener('click', function() {
  stripe.redirectToCheckout({
    sessionId: '<%= @session.id %>'
  }).then(function (result) {
  });
//});

app/views/flights/index.html.erb
<section>
<%= form_with url: "/flights", method: :get do |f| %>
  <%= f.label :from_airport, "From airport code:" %>
  <%= f.select(:from_airport, options_for_select(@airport_codes, disabled:"0", selected:"0")) %>
  <%= f.label :to_airport, "To airport code:" %>
  <%= f.select(:to_airport, options_for_select(@airport_codes, disabled:"0", selected:"0")) %>
  <%= f.label :passengers %>
  <%= f.select :passengers, options_for_select(@passengers, disabled:"0", selected:"0")  %>
  <%= f.label :date %>
  <%= f.select :date, options_for_select(@dates, disabled:"Date", selected:"Date")  %>
  <%= f.submit "Search" %>
<% end %>
</section>
<% if @flights %>
  <section>
    
    <%= form_with url: bookings_path, method: :get do |f| %>
      <%= f.hidden_field :passengers, value: params[:passengers] || 1 %>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">From</th>
            <th scope="col">To</th>
            <th scope="col">Duration</th>
            <th scope="col">Price</th>
            <th scope="col">Start-Datetime</th>
            <th scope="col">Seats-Left</th>
            <th scope="col">Select</th>
          </tr>
        </thead>
        <tbody>
          <% @flights.each do |flight| %>
            <tr>
              <th scope="row"><%= flight.id %></th>
              <td><%= flight.departure_airport.code %></td>
              <td><%= flight.arrival_airport.code %></td>
              <td><%= flight.duration.floor %> hours <%= (flight.duration.modulo(1)*60).to_i %> minutes</td>
              <td>$<%= flight.price.to_f.round(2) %></td>
              <td><%= flight.start_datetime %></td>
              <td><%= flight.seats_left %></td>
              <td><%= f.radio_button :flight_id, flight.id, required: true %></td>
            </tr>
          <% end %>
          <% if @flights.empty? %>
            <tr>
              <td colspan="8" style="text-align:center">No match for Flights</td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= f.submit "Book Flight" %>
    <% end %>
  </section>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://js.stripe.com/v3/"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>